version: '3.8'

services:
  # Фронтенд сервер
  frontend:
    build:
      context: ./Children
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./Children:/app
      - /app/node_modules  # Для React/Vue, если используете
    environment:
      - NODE_ENV=development
    restart: unless-stopped
    networks:
      - app-network

  # Бэкенд сервер
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./backend/app:/app/app
      - ./backend/requirements.txt:/app/requirements.txt
    environment:
      - PYTHONPATH=/app
      - ENVIRONMENT=development
    restart: unless-stopped
    networks:
      - app-network

networks:
  app-network:
    driver: bridge